server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**
        - id: lot-service
          uri: lb://lot-service
          predicates:
            - Path=/lots/**
        - id: bid-service
          uri: lb://bid-service
          predicates:
            - Path=/bids/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

